<a href="https://colab.research.google.com/github/riyakothari/Pytorch-implementations/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Title Here

### Subtitle Here

An short introduction about PyTorch and about the chosen functions. 
- function 1
- function 2
- function 3
- function 4
- function 5

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor (change this)

Add some explanations

In [6]:
# torch.new_ones
tensor = torch.tensor((), dtype=torch.int32)
tensor.new_ones(size=[2,3])

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

new_ones is a method of torch.tensor class that creates a tensor of size which is provided as an argument, and fills the newly created tensor with values 1. Here, a tensor of size (2,3) is being created and as evident from the result, all values are 1.

In [8]:
tensor.new_ones(size=(2,2,3), requires_grad=True, dtype=torch.float32)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]], requires_grad=True)

In this example, I have created a 3-dimensional tensor, and all the values in the tensor are set to 1. Here I have also provided the requires_grad parameter and set it to True, so that pytorch will remember all the operations done on this tensor.

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
tensor.new_ones(size=(2,2,3), requires_grad=True)

RuntimeError: ignored

This example is essentially the same as the above one, with the removal of the dtype parameter. In order for pytorch to remember the operations, the type of the tensor needs to be floating point, but our tensor was an integer, so with the removal of dtype parameter, it throws an error.

Thsi function can be used while creating a new tensor whose values need to be one.


## Function 2 - torch.abs()

This function returns the absolute values of all the values in the tensor.

In [10]:
tensor = torch.tensor([[-1., -5.], [-2., 3.]], dtype=torch.float32)
torch.abs(tensor)

tensor([[1., 5.],
        [2., 3.]])

As seen in the output, all the negative numbers are represented by the absolute values.

In [13]:
tensor = torch.tensor([[[-1., -5.], [-2., 3.]], [[0-2., 3.2], [1.1, -11]]], dtype=torch.float32)
torch.abs(tensor)

tensor([[[ 1.0000,  5.0000],
         [ 2.0000,  3.0000]],

        [[ 2.0000,  3.2000],
         [ 1.1000, 11.0000]]])


Similarly, in this example also, al negatives have been converted to positive numbers.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.tensor([[-1., -5.], [-2., 3.], ], dtype=torch.float32)
tensor = tensor.numpy()
torch.abs(tensor, out=tensor)

TypeError: ignored

The input to this function should be a tensor, and as in this example, I am sending a numpy array to it, the function gives out an error.

Used when all values need to be positive in a tensor.

## Function 3 - torch.eq()

Used to find out if two tensors are exactly the same, element-wise.

In [20]:
# Example 1 - working
tensor1 = torch.tensor([[-1., -5.], [-2., 3.]], dtype=torch.float32)
tensor2 = torch.tensor([[-1., -5.], [-2., 3.]], dtype=torch.float32)
torch.eq(tensor1, tensor2)

tensor([[True, True],
        [True, True]])


In this example, both the tensors are exactly thr same, so this function returns a tensor of same size, with all elements set to True, as all the elements of the two tensors match perfectly.

In [31]:
# Example 2 - working
tensor1 = torch.tensor([[-1., -5.], [-2., 3.]], dtype=torch.float32)
tensor2 = torch.tensor([[-1, -3]], dtype=torch.int32)
torch.eq(tensor1, tensor2)

tensor([[ True, False],
        [False, False]])

In this example, the second value of first column doesn't match, and so in the result the value of that position is False, while others are still true. Note that it broadcasts the shape of tensor2 to that of tensor1.

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
tensor1 = torch.tensor((), dtype=torch.float32)
tensor2 = torch.tensor((), dtype=torch.int32)
tensor1 = tensor1.new_ones((5,2,4,1))
tensor2 = tensor2.new_ones(( 3,1,1))
torch.eq(tensor2, tensor1)

RuntimeError: ignored

This example gives out an error, as the shapes of the two tensors are different and can't be broadcasted into one another.

To check the element-wise equality of two tensors.

## Function 4 - torch.flatten()

Flattens a contigous set of dimensions of a tensor, converting those dimentions into a single dimension

In [32]:
# Example 1 - working
tensor = torch.tensor([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]])
torch.flatten(tensor)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

The original tenosr was of size (2,2,2), but the resulting tensor is flattened into a dimention of (1,8)

In [33]:
# Example 2 - working
t = torch.tensor([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]])
torch.flatten(t, 1,2)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

This example specifies the start and end dimensions to be flattened, and so the 0th dimention remains the same, but dim 1 and 2 are flattened.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
t = torch.tensor([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]])
torch.flatten(t, 2,3)

IndexError: ignored

Be careful of the dimesions provided, as it will give an error if the dimensions are not in range. They are zero-indexed.

Converting the tensor into a simpler stacked up version of the original .



## Function 5 - torch.reciprocal()

Outputs the reciprocal of a tensor.

In [37]:
# Example 1 - working
a = torch.randn(4)
print(a)
torch.reciprocal(a)

tensor([-0.7535,  0.7546,  1.1911, -0.6182])


tensor([-1.3271,  1.3253,  0.8396, -1.6177])

Simply returns the reciprocal of the tensor.

In [38]:
# Example 2 - working
a = torch.randn((2,3))
print(a)
torch.reciprocal(a)

tensor([[ 0.6655, -0.0745,  0.3085],
        [ 0.2911,  0.7403, -0.6925]])


tensor([[  1.5025, -13.4183,   3.2415],
        [  3.4347,   1.3508,  -1.4440]])

The output is of the same size as teh input, but they are the reciprocates of one another.

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
a = tensor.new_zeros((2,3))
print(a)
torch.reciprocal(a)

tensor([[0, 0, 0],
        [0, 0, 0]])


RuntimeError: ignored

The reciprocal of a zero matrix does not exist, and so the error

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [40]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 71kB 2.0MB/s 


In [41]:
import jovian

In [43]:
jovian.commit(project = 'assignment1')

[jovian] Detected Colab notebook...


[jovian] Error: Colab File Id is not provided


[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...


ApiError: ignored